# File: gurbani-insight/docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    container_name: gurbani-insight-app
    restart: unless-stopped
    ports:
      - "${PORT:-8001}:8001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/chroma_db:/app/chroma_db
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/data:/app/data
    environment:
      - CHROMA_DB_PATH=/app/chroma_db
      - COLLECTION_NAME=${COLLECTION_NAME:-gurbani_english_enhanced}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-nomic-embed-text}
      - OLLAMA_API_URL=http://ollama:11434/api/embeddings
      - CSV_PATH=/app/data/gurbani_english_enhanced_chunks.csv
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: gurbani-insight-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/ollama:/root/.ollama
    command: serve

volumes:
  chroma_db:
  ollama: